notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/bd77a26eab56de803949
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

language: bash

before_install:
  - rm -rf ~/.gnupg

before_script:
  - sudo apt-get -qq purge mysql* graphviz*
  - sudo apt-get -qq autoremove

script:
  - sudo echo -e "[user]\n\tname = abc\n\temail = root@localhost.com" > ~/.gitconfig
  - sudo echo "Travis Banch = $TRAVIS_BRANCH"
  - sudo apt-get install git python3-setuptools python3-dev python3-apt
  - sudo python3 setup.py install
  - sudo ee --help
